export const buildingCodes = new Map([
    ["ACT", "Art, Culture & Technology"],
    ["AIRB", "Anteater Instruction & Research Building"],
    ["AITR", "Arts Instruction & Technology Resource Center"],
    ["ALH", "Aldrich Hall"],
    ["ALP", "Anteater Learning Pavillion"],
    ["APL", "Air Pollution Labs"],
    ["ARAN", "Arts Annex"],
    ["ARBO", "Arboretum (North Campus)"],
    ["ARC", "Anteater Recreation Center"],
    ["ART", "Art Studio"],
    ["BH", "Berk Hall"],
    ["BIMO", "Bison Modular"],
    ["BLI", "Beckman Laser Institute"],
    ["BOAT", "Boat House"],
    ["BRL", "Bonney Research Laboratory (CNLM)"],
    ["BS3", "Biological Sciences III"],
    ["CD", "Child Development Center (North Campus)"],
    ["CH", "Crawford Hall"],
    ["CNLM", "Center for the Neurobiology of Learning and Memory"],
    ["QRL", "Qureshey Research Laboratory"],
    ["CRCC", "Cross-Cultural Center"],
    ["CRH", "Croul Hall"],
    ["CTT", "(Claire) Trevor Theatre"],
    ["CV", "Campus Village"],
    ["DBH", "(Donald) Bren Hall"],
    ["DRA", "Drama Building"],
    ["DS", "Dance Studios"],
    ["ECT", "Engineering & Computing Trailer"],
    ["EDUC", "Education Building"],
    ["EG", "Engineering Gateway"],
    ["EH", "Engineering Hall"],
    ["ELF", "Engineering Laboratory Facility"],
    ["ELH", "Engineering Lecture Hall"],
    ["ET", "Engineering Tower"],
    ["FARMSCHOOL", "Farm School/Red Barn"],
    ["FRF", "Faculty Research Facility (North Campus)"],
    ["FRH", "(Frederick) Reines Hall"],
    ["GNRF", "Gillespie Neuroscience Research Facility"],
    ["HG", "Humanities Gateway"],
    ["HH", "Humanities Hall"],
    ["HIB", "Humanities Instructional Building"],
    ["HICF", "Humanities Interim Classroom Facility"],
    ["HRH", "Hewitt Research Hall"],
    ["HSLH", "(Howard) Schneiderman Lecture Hall"],
    ["IAB", "Intercollegiate Athletics Building"],
    ["ICF", "Interim Classroom Facility"],
    ["ICS", "Information & Computer Science"],
    ["ICS2", "Information & Computer Science II"],
    ["IH", "Irvine Hall"],
    ["KH", "Krieger Hall"],
    ["LAW", "Law Building"],
    ["LLIB", "Langson Library"],
    ["MAB", "Mesa Arts Building"],
    ["MDE", "McDonnell Douglas Engineering Auditorium"],
    ["MH", "McGaugh Hall"],
    ["MM", "Music & Media Building"],
    ["MPAA", "Multipurpose Academic and Administrative Building"],
    ["MS1", "Medical Surge I"],
    ["MS2", "Medical Surge II"],
    ["MS-A", "Medical Sciences A"],
    ["MS-B", "Medical Sciences B"],
    ["MS-C", "Medical Sciences C"],
    ["MS-D", "Medical Sciences D"],
    ["MS-E", "Medical Sciences E"],
    ["MSTB", "Multipurpose Science & Technology Building"],
    ["NS1", "Natural Sciences I"],
    ["NS2", "Natural Sciences II"],
    ["ON", "Online"],
    ["PCB", "Parkview Classroom Building"],
    ["PH", "Plumwood House"],
    ["PSCB", "Physical Sciences Classroom Building"],
    ["PSLH", "Physical Sciences Lecture Hall"],
    ["PSTU", "Performance Studios"],
    ["REC", "Rockwell Engineering Center"],
    ["RH", "Rowland Hall"],
    ["SAIL", "Sail Base"],
    ["SB", "Merage School of Business"],
    ["SC CCA", "Student Center Crystal Cove Auditorium"],
    ["SCS", "Sculpture and Ceramic Studios"],
    ["SE", "Social Ecology I"],
    ["SE2", "Social Ecology II"],
    ["SH", "Steinhaus Hall"],
    ["SLIB", "Science Library"],
    ["SPH", "Sprague Hall"],
    ["SS1", "Student Services I"],
    ["SS2", "Student Services II"],
    ["SSH", "Social Science Hall"],
    ["SSL", "Social Science Laboratory"],
    ["SSLH", "Social Science Lecture Hall"],
    ["SSPA", "Social Science Plaza A"],
    ["SSPB", "Social Science Plaza B"],
    ["SST", "Social Science Tower"],
    ["SSTR", "Social Science Trailer"],
    ["STU4", "Studio Four"],
    ["TBA", "To be arranged"],
    ["UCI BARN", "Farm School/Red Barn"],
    ["UCI MC", "UCI Medical Center"],
    ["UNEXA", "University Extension A"],
    ["WSH", "(Winifred) Smith Hall"]
]);
